version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: cityhotel-postgres
    environment:
      POSTGRES_DB: CityHotelGarageDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4512
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cityhotel-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d CityHotelGarageDB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped

  # .NET API with JWT
  api:
    build:
      context: ..  # Üst dizine git (Business klasörünü de içerecek)
      dockerfile: CityHotelGarageAPI/Dockerfile  # Dockerfile'ın tam yolu
    container_name: cityhotel-api
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # ASP.NET Core ayarları
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5010
      
      # Database connection
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=CityHotelGarageDB;Username=postgres;Password=4512;Pooling=true;MinPoolSize=1;MaxPoolSize=20;CommandTimeout=60;
      
      # JWT Configuration - Basitleştirilmiş
      - JWT__SecretKey=MyVerySecureSecretKey2024ForCityHotelGarageAPI!
      - JWT__Issuer=CityHotelGarageAPI
      - JWT__Audience=CityHotelGarageUsers
      - JWT__ExpiryMinutes=60
      
      # CORS
      - CORS__AllowedOrigins=http://localhost:3000,http://localhost:5173,http://localhost:8080
    ports:
      - "5010:5010"  # ✅ EKSIK OLAN PORT MAPPING
    networks:
      - cityhotel-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5010/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:

networks:
  cityhotel-network:
    driver: bridge